import type { ProjectConfig } from '/#/config';
import {
  ContentEnum,
  PermissionModeEnum,
  RouterTransitionEnum,
  SettingButtonPositionEnum,
  ThemeEnum,
} from '/@/enums/appEnum';
import { MenuModeEnum, MenuTypeEnum, MixSidebarTriggerEnum, TriggerEnum } from '/@/enums/menuEnum';

// ! You need to clear the browser cache after the change
const setting: ProjectConfig = {
  showSettingButton: true,
  showDarkModeToggle: true,
  // "settingButtonPosition": "auto",
  settingButtonPosition: SettingButtonPositionEnum.AUTO,
  // "permissionMode": "ROUTE_MAPPING",
  permissionMode: PermissionModeEnum.ROUTE_MAPPING,
  permissionCacheType: 1,
  sessionTimeoutProcessing: 0,
  themeColor: '#0960bd',
  grayMode: false,
  colorWeak: false,
  fullContent: false,
  // "contentMode": "full",
  contentMode: ContentEnum.FULL,
  showLogo: true,
  showFooter: false,
  headerSetting: {
    bgColor: '#ffffff',
    fixed: true,
    show: true,
    // "theme": "light",
    theme: ThemeEnum.LIGHT,
    useLockPage: true,
    showFullScreen: true,
    showDoc: true,
    showNotice: true,
    showSearch: false,
  },
  menuSetting: {
    bgColor: '#001529',
    fixed: true,
    collapsed: false,
    collapsedShowTitle: false,
    canDrag: false,
    show: true,
    hidden: false,
    menuWidth: 210,
    // "mode": "inline",
    mode: MenuModeEnum.INLINE,
    // "type": "sidebar",
    type: MenuTypeEnum.SIDEBAR,
    // "theme": "dark",
    theme: ThemeEnum.DARK,
    split: false,
    topMenuAlign: 'center',
    // "trigger": "FOOTER",
    trigger: TriggerEnum.FOOTER,
    accordion: true,
    closeMixSidebarOnChange: false,
    // "mixSideTrigger": "click",
    mixSideTrigger: MixSidebarTriggerEnum.CLICK,
    mixSideFixed: false,
  },
  multiTabsSetting: {
    cache: false,
    show: false,
    canDrag: true,
    showQuick: true,
    showRedo: true,
    showFold: true,
  },
  transitionSetting: {
    enable: true,
    // "basicTransition": "fade-slide",
    basicTransition: RouterTransitionEnum.FADE_SIDE,
    openPageLoading: true,
    openNProgress: true,
  },
  openKeepAlive: true,
  lockTime: 0,
  showBreadCrumb: false,
  showBreadCrumbIcon: false,
  useErrorHandle: false,
  useOpenBackTop: true,
  canEmbedIFramePage: true,
  closeMessageOnSwitch: true,
  removeAllHttpPending: false,
};

export default setting;
